version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: people
        container_name: people-app
        restart: unless-stopped
        working_dir: /var/www/people
        volumes:
            - ./:/var/www/people
        networks:
            - people
    db:
        image: mysql:8.0
        container_name: people-db
        restart: on-failure
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - my-datavolume:/var/lib/mysql
        ports:
            - ${DB_HOST_PORT:-3306}:3306
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        networks:
            - people
    nginx:
        image: nginx:1.18.0-alpine
        container_name: people-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/people/public
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        networks:
            - people
networks:
    people:
        driver: bridge
volumes:
    my-datavolume:
